id: P002996
initial_creation_type: ocr
source_metadata:
  id: bdr:W4CZ7100
  title: ཐུགས་ཆེན་བདེ་འདུས་ཀྱི་སྒྲུབ་ཐབས་རྣམ་བཤད།
  author: ''
  volumes:
    7f75813677d54c4d89a94794578da4c1:
      image_group_id: I1KG9726
      title: ''
      volume_number: 1
      total_pages: 454
      base_file: v001.txt
