id: P002996
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-17 10:33:20.270616
source_metadata:
  id: bdr:W4CZ7100
  title: ཐུགས་ཆེན་བདེ་འདུས་ཀྱི་སྒྲུབ་ཐབས་རྣམ་བཤད།
  author: ''
  volumes:
    7f75813677d54c4d89a94794578da4c1:
      image_group_id: I1KG9726
      title: ''
      volume_number: 1
      total_pages: 454
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
