id: I466DFFDC
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T00:51:36+00:00'
last_modified: '2022-06-07T16:52:20.418898+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W4CZ7100
  title: ཐུགས་ཆེན་བདེ་འདུས་ཀྱི་སྒྲུབ་ཐབས་རྣམ་བཤད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    D99D:
      image_group_id: I1KG9726
      title: ''
      total_pages: 454
      order: 1
      base_file: D99D.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
